### ISSUE TITLE
Common trie: Model answer box can be too narrow for the full graph

### ISSUE THREAD

**Issue by Meratyn** [Aalto-LeTech/jsav-exercise-recorder#140]
Example:

![Screenshot from 2023-06-07 09-56-44](https://github.com/Aalto-LeTech/jsav-exercise-recorder/assets/48283121/b22143e2-cb21-4f3f-bc95-c433ba8dfa96)

**Comment by atilante** [comment]
I tested this manually with a couple of model answers. Indeed, this seems to work.
