### ISSUE TITLE
Heapsort: model answer narration partially invisible

### ISSUE THREAD

**Issue by atilante** [Aalto-LeTech/jsav-exercise-recorder#157]
The third row of narration is not visible in the model answer of the Heapsort exercise.

![heapsort-model-answer-narration](https://github.com/Aalto-LeTech/jsav-exercise-recorder/assets/3034945/cb9c3b6a-1402-4ae7-ae75-3512746d4f19)

**Comment by Meratyn** [comment]
This one is a duplicate of #136 , which is solved with the (open) pull request #143 .
