### ISSUE TITLE
DFS & BFS: add an adjacency list representation of the graph

### ISSUE THREAD

**Issue by atilante** [Aalto-LeTech/jsav-exercise-recorder#180]
Archie: "Could we remove the alphabetical order (in instructions) from DFS and BFS by providing the graph also as a neighbour list? This might be one issue, low priority. Besides, in DFS the visual layout of the exercise has quite much empty space."

Depth-first search & breadth-first search: If there is an adjacency list representation of the graph in addition to the node-link diagram visualization, it is explicit to the student why the nodes are processed in the alphabetic order. / Discussion 13.6.2024 with Archie: Indeed, there should be an adjacency list which is represented as text in monospace font. One could even extend the existing pseudocode block. E.g.

```
A: B C D F G
B: A D E
C: A E G I
D: A B
E: B C
F: A
G: A C H
H: G
I: C
```

- [x] DFS: add an adjacency list representation
- [x] DFS: modify exercise instructions
- [ ] DFS: modify model answer
- [x] BFS: add an adjacency list representation
- [x] BFS: modify exercise instructions
- [ ] BFS: modify model answer

**Comment by ttaiv** [comment]
Adjacency list representation has bee added in pull request #260. Model answer could be further improved by adding the adjacency list to it and highlighting the current node from the list at each step.

**Comment by ttaiv** [comment]
Created a separate issue of adding adjacency list to the model solution.
