### ISSUE TITLE
Nonscaffolded Dijkstra: unreliable grading

### ISSUE THREAD

**Issue by atilantera** [Aalto-LeTech/jsav-exercise-recorder#192]
12.1.2: Non-scaffolded Dijkstra: assari Vertti Laitisen mukaan tehtävästä oli
vaikea saada täysiä pisteitä.

https://plus.cs.aalto.fi/a1141/2023/lisatehtavat/dijkstra_simulation_bonus/dijkstras_algorithm_nonscaffolded/submissions/

**Comment by atilante** [comment]
Tämä ratkaistiin dijkstra-misconceptions -repossa.
