### ISSUE TITLE
Dijkstra: fix GUI bugs

### ISSUE THREAD

**Issue by atilantera** [Aalto-LeTech/jsav-exercise-recorder#198]
Based on issue #197

The legend for model answer appears in the exercise view during grading. Recreate the legend using JSAV APIs:
http://jsav.io/otherapis/label/
http://jsav.io/graphicalprimitives/rectangle/
http://jsav.io/graphicalprimitives/lines/

- [x] Text in binary heap nodes: swap node and its parent

Recreate the legend using JSAV APIs
- [ ] 
- [x] Remove elements' positioning to `div.flex`

**Comment by atilante** [comment]
SVG:         "shape-rendering": "crispedges"
