### ISSUE TITLE
DFS & BFS: graph as a neighbour list

### ISSUE THREAD

**Issue by atilante** [Aalto-LeTech/jsav-exercise-recorder#211]
Archie: "Saisiko aakkosjärjestyksen DFS:stä ja BFS:stä pois antamalla verkko vieruslistana? Tämä voisi olla yksi issue, ei korkea prioriteetti. DFS:ssä tehtävän elementtien asettelukin on turhan ilmava juuri nyt."

**Comment by atilante** [comment]
BFS reviewed with Archie: seems very good!

**Comment by ttaiv** [comment]
Duplicate of #180
