### ISSUE TITLE
DFS & BFS: highlight "visited" row

### ISSUE THREAD

**Issue by atilante** [Aalto-LeTech/jsav-exercise-recorder#212]
DFS: ja BFS: visited-rivi koodissa pitäisi korostaa, jotta opiskelija ymmärtää, millä rivillä koodia pitää tehdä käyttöliittymäoperaatio (JSAV:n termein: gradable step).

Katso mallia alkuperäisestä Primin algoritmi -tehtävästä: `testbench/OpenDSA/AV/Development/PrimAVPE.html`.

Lähdekoodi: PrimAVPE.js:19-24. Esim. näin:
```javaScript
  if (code) {
    pseudo = jsav.code($.extend({after: {element: $(".code")}}, code));
    pseudo.highlight(8)
  } else {
    pseudo = jsav.code();
  }

```
- [x] GraphAlgorithms.css: rename or remove selector `.jsavcodeline.action`
- [x] DFS (pseudocode in the exercise)
- [x] BFS (pseudocode in the exercise)

**Comment by ttaiv** [comment]
Would term "target node" in the exercise instructions be suitable for fixing the inconsistency that (a) the pseudocode highlights **visiting a node**  as operation that the user should do, but (b) the user actually clicks **edges**? When clicking an edge, there is a node which is already in the spanning tree (or DFS/BFS tree), and the other node would be the "target node" (which is unvisited).
