### ISSUE TITLE
Pseudocode to Prim-PQ

### ISSUE THREAD

**Issue by atilante** [Aalto-LeTech/jsav-exercise-recorder#213]
![Prim-PQ-with-pseudocode](https://github.com/Aalto-LeTech/jsav-exercise-recorder/assets/3034945/41b9f656-1d0d-4419-a5f9-e89d46654446)

**What**: Add pseudocode to the Prim's algorithm exercise with a priority queue. Highlight the rows that represent the actions that the student should simulate. (`update or insert v into Q` and `u := remove from ...`) The picture above is an edited screenshot of the GUI of Prim-PQ exercise with relevant pseudocode box added and correct lines highlighted.

**Why:**: We (archie, Artturi) assume that highlighted pseudocode would support the student to understand the pseudocode.

**Comment by atilante** [comment]
- This was done for PrimAVPE.* (Prim without priority queue) in issue #164 .
- If this is done for Prim With Priority Queue, it should be done for Dijkstra With Priority Queue as well for consistency.
- The problem is that the user interface of the priority queue versions of Prim and Dijkstra are already quite complex.

**Comment by atilante** [comment]
Archie needed: a comment for exercise design.

**Comment by ttaiv** [comment]
The GUI would become too crowded.
