### ISSUE TITLE
BFS: queue in the model answer

### ISSUE THREAD

**Issue by atilante** [Aalto-LeTech/jsav-exercise-recorder#218]
![BFS-queue-contents](https://github.com/Aalto-LeTech/jsav-exercise-recorder/assets/3034945/3d76faaf-e126-4541-82c8-1deae2da4e56)
The model answer of breadth-first search exercise could display the contents of the queue. The photograph here shows Archie's example of consecutive states of the queue.

The breadth-first search exercise is located in the repository at `testbench/OpenDSA/AV/Development/graphBFSPE.*

Task list for Teemu:

- [x] Move this issue card into the **In progress** column at [the classic project view in GitHub](https://github.com/Aalto-LeTech/jsav-exercise-recorder/projects/1)
- [x] Create a new git branch for the issue (jsav-exercise-recorder repo)
- [x] Clone the [JSAV repository](https://github.com/vkaravir/JSAV/). (Note: independent of jsav-exercise-recorder)
- [x] Modify `examples/list.html` in the JSAV repository to produce a simple JSAV animation of a stack (empty stack, elements pushed, elements popped). See the local file `JSAV-exercise-notes.md`in the jsav-exercise-recorder repo for a developer manual.
- [x] Read about [why git commit messages matter](https://cbea.ms/git-commit/)
- [x] Add an empty JSAV list in the model answer of the BFS exercise ((jsav-exercise-recorder repo)
- [x] Make the model answer push and remove items from the list (jsav-exercise-recorder repo)
- [x] Push your branch to Github
- [x] Create a pull request from the issue branch to branch `jaal2.0`
- [x] Notify Artturi

**Comment by atilante** [comment]
Archie needed: the queue is now visualized as a linked list. Is this good enough?

**Comment by atilante** [comment]
Archie:
- legendit sille, mikä on visited (pseudokoodiin verraten)
- listavisualisaatio: pitäisi olla seliteteksti: "Jono"
- joo, tehtävänannossa voisi mainita kaaren (u,v) jossa v on naapuri
- edellisen lisäksi pseudokoodiin kommentti: silmukassa on kaari (u,v)
- issueen #245 liittyen: joo, vaihda kaikkien  verkkoalgoritmitehtävien tehtävänantoihin samanlainen kaarinotaatio

Ari tarkastelisi verkkoalgoritmitehtäviä kokonaisuutena. Toive: kaikki pseudokoodin elementit olisi visualisoitu. Entä jos finished-solmut olisi merkattu kolmannella värillä?

**Comment by ttaiv** [comment]
Queue visualization https://tarjotin.cs.aalto.fi/cs-a1141/OpenDSA/Books/CS-A1141/html/QueueLinked.html

**Comment by atilante** [comment]
Ari visualisoisi DFS:ssä stackin samalla tavalla, jos toteutus on yksisuuntainen linkitetty lista: lisäys ja poisto alkuun.

**Comment by atilante** [comment]
Idea monivalintatehtävästä: miten toteuttaisit jonon, jos on yksisuuntainen linkitetty lista? Entä pinon?

**Comment by ttaiv** [comment]
Actions taken based on discussion Artturi summarized above:
-  Opened a new issue #246 to improve the BFS model answer queue
-  Opened a new issue #247 to visualize the call stack in DFS model answer
-  Updated the issue #210 to request the visualization of visited flags in BFS and DFS.
