### ISSUE TITLE
Kruskal: remove the alpabet requirement

### ISSUE THREAD

**Issue by atilante** [Aalto-LeTech/jsav-exercise-recorder#252]
## Description

**What**: Could we remove the extra alphabet rule in the exercise instructions of Kruskal, as was done for Prim and Dijkstra in #189 and #191? I.e., the English instructions of [Kruskal's algorithm](https://plus.cs.aalto.fi/a1141/2023/verkot/etsi-liita-menetelma/#chapter-exercise-1) have the sentence: "In case of equal weights, select the edge that comes first in the alphabetical order". However, this rule is not part of the algorithm; it has been added to make the solution unique, because that is required by the default JSAV grader.

**Why**: Reasons to remove the alphabet rule:
1. As we know from our Dijkstra-misconceptions research, this is extra cognitive load which confuses students.
2. Kruskal's algorithm does not specify that the sorting algorithm should be stable.

**How**: Similar solution to Prim and Dijkstra (the priority queue version) could be used. If the existing code can be generalized, even better. Essentially, the default JSAV grader compares sequences of *states*. We would like to compare sequences (strings) of operations so that some operations can be in relative order.

## Example

![kruskal-example](https://github.com/Aalto-LeTech/jsav-exercise-recorder/assets/3034945/683a050d-3883-4821-9fdc-97a6dbd51595)

The model answer for the graph above has the steps described below.

```
No.  Action  Edge  Weight
--------------------------
 1   add     AB    1
 2   add     CF    1
 3   add     CH    1
 4   add     FK    2
 5   add     CD    3
 6   add     GK    3
 7   dismiss KH    4
 8   dismiss DH    5
 9   add     FI    6
10   add     BC    7
11   add     EI    7
12   dismiss AE    8
13   dismiss CG    8
14   add     IJ    9
```

Note that the "dismiss" steps are only in the model answer; they are not gradable. Therefore, the sequence of added edges is
```
(AB, CF, CH) FK (GD, GK) FI (BC, EI) IJ
```

Each subsequence in parentheses could have their elements in arbitrary order. E.g. all of these are would be correct solutions:
```
AB, CF, CH, FK, GD, GK, FI, BC, EI, IJ
CH, AB, CF, FK, GD, GK, FI, BC, EI, IJ
CH, AB, CF, FK, GD, GK, FI, EI, BC, IJ
```

**Comment by ttaiv** [comment]
Closed with #284
