### ISSUE TITLE
Scaffolded Prim: remove need to process nodes in alphabetic order

### ISSUE THREAD

**Issue by ttaiv** [Aalto-LeTech/jsav-exercise-recorder#253]
### Problem
The current version of Prim exercise (PrimAVPE-scaffolded-v2) does not usually require to process the neighbors of a node in alphabetic order. However, when two edges connecting the previously dequeued node to unvisited nodes happen to have the same weight, it is required to process them in alphabetic order to satisfy the grader.
![Screenshot from 2024-06-07 14-54-26](https://github.com/Aalto-LeTech/jsav-exercise-recorder/assets/136599271/cf42b1d2-5af1-415b-8a3d-caef1357a097)
Example: Here it is required to first enqueue K to satisfy the grader.

### Solution (edited)
Just add adjacency list representation of the graph --> emphasizes that the algorithm is deterministic and makes it clear what determines the processing order of the nodes. NOTE: the grading should now also be modified to require processing nodes in the order specified by adjacency list.

**Comment by ttaiv** [comment]
Unfortunately, it seems that the proposed solution is not sufficient to remove the need for alphabetic order.
For example in this situation:
![Screenshot from 2024-06-18 11-14-11](https://github.com/Aalto-LeTech/jsav-exercise-recorder/assets/136599271/6280676f-facb-4f21-829c-b197ef4686f8)

Enqueuing M, then N and pressing dequeue results to:

![Screenshot from 2024-06-18 11-14-40](https://github.com/Aalto-LeTech/jsav-exercise-recorder/assets/136599271/1723070b-fe7b-4c47-8600-1edec3920324)

That is, N is the highest priority element.

On the other hand, enqueuing first N, then M and pressing dequeue result to:

![Screenshot from 2024-06-18 11-15-05](https://github.com/Aalto-LeTech/jsav-exercise-recorder/assets/136599271/25b154b6-e8f4-4e9b-834f-a5accece9593)

That is, F being the highest priority element.

Possible solutions
- Make **all** the edge weights unique so that the order of elements in the PQ is always independent of enqueuing order.
- Revert back to version of PQ (MinHeapInterface) where position in alphabets influenced priority of element (again PQ order is independent of enqueuing order).
- Modify grading to create multiple model answers where nodes are processed in different order and compare the user's solution against them all.
- Just keep the alphabetic order requirement (and maybe consider adding neighbour list to determine the processing order of nodes).

**Comment by atilante** [comment]
An excellent finding! My comments on possible solutions:

**Solution 1. Unique edge weights**
+ Easy to implement: when there are |E| edges, generate an array of unique values 1...|E| and then shuffle it.
+ The solution is unique.
+ |E| ~ 20, so this would be doable.
+ No user interface modifications needed.

**Solution 2. Revert back to alphabetic order in priority queue**
+ Keeps everything as it is
- What happens inside the priority queue might puzzle a rare (unknown) minority of students.
+ However, the implementation of the priority queue is not a central learning objective of this exercise.

**Solution 3. Modify grading to create multiple model answers.**
+ Theoretically possible
- Brute force solution with combinatorics: based on empirical examinations of four model answers, there are at most 48 different solutions. (Yes, we would have to run Prim's algorithm 48 times, and create JSAV slideshows for each of those.)
* More elegant solution by time complexity might be achieved by extending the idea in Dijkstra-PQ exercise (v3)

**Solution 4. Keep the alphabetic order requirement**
+ If neighbour list added, the solution is unique
+ No need for complex grading algorithms
- Requires some user interface design & programming
- The user interface becomes more complex
* Consistency with other graph algorithm exercises?

Considering the options, I would choose Solution 2, unless Archie would like to have Solution 4 to emphasize the neighbour list.
