### ISSUE TITLE
Infinite loop: TypeError on parent.postMessage

### ISSUE THREAD

**Issue by atilante** [Aalto-LeTech/jsav-exercise-recorder#67]
Doing the exercise correctly to the point where the template edge MN is added,
  then clicking Remove does not seem to add a new edge to the spanning tree. It
  seems to set odsaAV-min.js:302 into an infinite loop with "Uncaught typeError:
  parent.postMessage is not a function"

**Comment by Meratyn** [comment]
If I remember correctly, I ran into the bug whilst working on updating the model solution and resolved it in #55 . I cannot reproduce the bug at this point
