### ISSUE TITLE
Require edges to be added to PQ in alphabetical order

### ISSUE THREAD

**Issue by atilante** [Aalto-LeTech/jsav-exercise-recorder#68]
Require edges to be added to the priority queue in alphabetical order.

Why:

Add first edge to tree, add nodes to PQ, Undo -> initial state. Confusing!
Solution: require edges to be processed in alphabetical order.

How:

Adding and updating an edge to the priority queue must be a gradeable step.

- [x] add `av.gradeableStep();` when the model solution adds or updates the PQ
- [x] add `exercise.gradeableStep();` when the user adds or updates the PQ
- [x] ensure that exactly the graph and the PQ are compared in the grading. Graph is compared by CSS property, PQ is compared by contents.
- [x] Test that doing the exercise correctly with neighbours in alphabetical order results in full points
- [x] Test that doing the exercise correctly with neighbours in nonalphabetical order results in full points
- [x] Update exercise instructions

**Comment by Meratyn** [comment]
This is because of JSAV's behaviour where "Undo" reverts to the previous gradable step state. This means that if something is done after a gradable step but no new gradable step has been triggered yet, JSAV reverts to the state in the penultimate gradable step.

**Comment by atilante** [comment]
How to solve:
1. If JSAV has a `exercise.step()` function similar to the `modelAnswer.step()` (not a gradeable step, see function markEdge in DijkstraPE-research-v2.js), then try to use that.
2. Otherwise accept this bug as a feature. Add a note in the learning material for students that this is a feature: Clicking Undo removes all recently added nodes.

**Comment by Meratyn** [comment]
`exercise.step()` does not seem to exist. It seems like this is indeed not a bug but a feature of JSAV.

**Comment by atilante** [comment]
Discussed on Monday 15 August in the study design meeting:

- Gradeable steps with Undo is a JSAV feature.
- Add first edge to tree, add nodes to PQ, Undo -> initial state. Confusing!
Solution: require edges to be processed in alphabetical order.

I have updated the description of the issue.
