### ISSUE TITLE
Dijkstra: Finnish translations of labels

### ISSUE THREAD

**Issue by atilante** [Aalto-LeTech/jsav-exercise-recorder#73]
![english-text-to-finnish](https://user-images.githubusercontent.com/3034945/185103103-52678788-bbe0-47ff-bc80-4729bd46613e.png)

Node = Solmu
Distance = Etäisyys
Parent = Vanhempi
Priority Queue = Prioriteettijono

**Comment by Meratyn** [comment]
![Screenshot from 2022-08-17 16-28-41](https://user-images.githubusercontent.com/48283121/185146370-14f25e77-2efd-4128-baa1-cf795d436d19.png)


There's one more string: Edge
What's the Finnish translation of that one?
